name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os_sdk: [freertos, mbed, zephyr]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.${{ matrix.os_sdk }} -t myapp/${{ matrix.os_sdk }} .

      - name: Run tests
        run: |
          # Add commands to run tests for each application
          echo "Running tests for ${{ matrix.os_sdk }} application"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        run: |
          # Add commands to set up kubectl and configure access to your cluster
          echo "Setting up Kubernetes"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/${{ matrix.os_sdk }}-deployment.yaml
          echo "Deployed ${{ matrix.os_sdk }} application to Kubernetes"