apiVersion: apps/v1
kind: Deployment
metadata:
  name: zephyr-app
  labels:
    app: zephyr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zephyr
  template:
    metadata:
      labels:
        app: zephyr
    spec:
      containers:
      - name: zephyr-container
        image: zephyr-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR_NAME
          value: "value"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"